# Generated by Django 3.2.13 on 2023-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='---', max_length=256)),
                ('estado', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
