# Generated by Django 3.2.13 on 2023-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0002_auto_20230804_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(default='---', max_length=64),
        ),
    ]
